//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        private int CargoField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((this.CargoField.Equals(value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLogin.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login_user_service", ReplyAction="*")]
        CapaGUI.ServiceLogin.login_user_serviceResponse login_user_service(CapaGUI.ServiceLogin.login_user_serviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login_user_service", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceLogin.login_user_serviceResponse> login_user_serviceAsync(CapaGUI.ServiceLogin.login_user_serviceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login_user_serviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login_user_service", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceLogin.login_user_serviceRequestBody Body;
        
        public login_user_serviceRequest() {
        }
        
        public login_user_serviceRequest(CapaGUI.ServiceLogin.login_user_serviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class login_user_serviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public login_user_serviceRequestBody() {
        }
        
        public login_user_serviceRequestBody(string nombre, string contraseña) {
            this.nombre = nombre;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login_user_serviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login_user_serviceResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceLogin.login_user_serviceResponseBody Body;
        
        public login_user_serviceResponse() {
        }
        
        public login_user_serviceResponse(CapaGUI.ServiceLogin.login_user_serviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class login_user_serviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceLogin.Usuario login_user_serviceResult;
        
        public login_user_serviceResponseBody() {
        }
        
        public login_user_serviceResponseBody(CapaGUI.ServiceLogin.Usuario login_user_serviceResult) {
            this.login_user_serviceResult = login_user_serviceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CapaGUI.ServiceLogin.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceLogin.WebService1Soap>, CapaGUI.ServiceLogin.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceLogin.login_user_serviceResponse CapaGUI.ServiceLogin.WebService1Soap.login_user_service(CapaGUI.ServiceLogin.login_user_serviceRequest request) {
            return base.Channel.login_user_service(request);
        }
        
        public CapaGUI.ServiceLogin.Usuario login_user_service(string nombre, string contraseña) {
            CapaGUI.ServiceLogin.login_user_serviceRequest inValue = new CapaGUI.ServiceLogin.login_user_serviceRequest();
            inValue.Body = new CapaGUI.ServiceLogin.login_user_serviceRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.contraseña = contraseña;
            CapaGUI.ServiceLogin.login_user_serviceResponse retVal = ((CapaGUI.ServiceLogin.WebService1Soap)(this)).login_user_service(inValue);
            return retVal.Body.login_user_serviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceLogin.login_user_serviceResponse> CapaGUI.ServiceLogin.WebService1Soap.login_user_serviceAsync(CapaGUI.ServiceLogin.login_user_serviceRequest request) {
            return base.Channel.login_user_serviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceLogin.login_user_serviceResponse> login_user_serviceAsync(string nombre, string contraseña) {
            CapaGUI.ServiceLogin.login_user_serviceRequest inValue = new CapaGUI.ServiceLogin.login_user_serviceRequest();
            inValue.Body = new CapaGUI.ServiceLogin.login_user_serviceRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.contraseña = contraseña;
            return ((CapaGUI.ServiceLogin.WebService1Soap)(this)).login_user_serviceAsync(inValue);
        }
    }
}
